app:
  name: "web_app"
  mode: "dev"
  port: 8081
  start_time: "2020-07-01"
  machine_id: 1

log:
  level: "debug"
  filename: "./bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "bluebell"
  max_open_conn: 200
  max_idle_conn:  100

redis:
  host: "192.168.56.128"
  port: 6379
  password: "dengliwei"
  db: 0
  pool_size: 10

